### PR TITLE
Version bump to 1.8.3.

### PR DESCRIPTION
**Pull request by dorner**
We've been running 1.8.2-beta2 in prod for a week or two (including with a BatchHandler) and everything seems fine.

### CODE REVIEW

**Comment by dorner** [comment]
@klippx Any update here?

**Comment by klippx** [comment]
Shouldnt this be 1.8.2? This is what the beta has been for and the latest was 1.8.1

**Comment by dorner** [comment]
@klippx sorry for the delay, was on vacation. Fixed the version, thanks!

**Comment by dorner** [comment]
@klippx any update? Been quite a while waiting for this.

**Comment by klippx** [comment]
Hello! I have also been on vacation :)

**Pull request merged**
